server:
  port: 8080
zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    resource1:
      path: /resource1/**
      url: http://localhost:8082/resourceserver1
    oauth:
      path: /oauth/**
      url: http://localhost:8081/oauthserver/oauth
security:
  oauth2:
    resource:
      jwt:
        key-value: 123

logging.level.org.springframework.security: DEBUG